Changes from the group.
------------------------------------------------------------------------
r11069 | sanjay.bhatnagar | 2010-04-12 12:17:09 -0600 (Mon, 12 Apr 2010) | 14 lines
Changed paths:
   M /active/casacore/ms/MeasurementSets/MSSelection.h
   M /active/casacore/ms/MeasurementSets/MSSelectionTools.h


       New Development: No
            JIRA Issue: Yes CAS-2111
      Ready to Release: Yes
     Interface Changes: No
What Interface Changed: Please list interface changes
         Test Programs: List test programs
  Put in Release Notes: Yes
             Module(s): Module Names change impacts.
           Description: Describe your changes here...

Added some documentation and improved some of the existing ones.


r11070 | rob.reid | 2010-04-12 12:33:54 -0600 (Mon, 12 Apr 2010) | 19 lines
Changed paths:
   M /active/casacore/msfits/MSFits/MSFitsOutput.cc
   M /active/casacore/msfits/MSFits/MSFitsOutput.h


       New Development: No
            JIRA Issue: Yes CAS-1686, 2048, & 2103
      Ready to Release: No, because it's a feature
     Interface Changes: Yes
What Interface Changed: exportuvfits and ms.tofits get new (sub)param
         Test Programs: ngc5921uvcontsub2 regression
  Put in Release Notes: Yes, but maybe not just yet.
             Module(s): msfits
           Description: This is probably harmless for 3.0.1, but it is
                        intended for active and 3.0.2.

                        Adds the padwithflags subparameter for filling
                        in missing data with flags as necessary to fit
                        the IF structure when combinespw is True.

	


r11072 | rob.reid | 2010-04-12 14:33:22 -0600 (Mon, 12 Apr 2010) | 16 lines
Changed paths:
   M /active/casacore/msfits/MSFits/MSFitsOutput.cc


       New Development: No
            JIRA Issue: Yes CAS-2048
      Ready to Release: No, but OK for casapy-test
     Interface Changes: No
What Interface Changed: 
         Test Programs: exportuvfits
  Put in Release Notes: No
             Module(s): msfits
           Description: Softens a safety test that was sometimes preventing
                        padwithflags from doing its job.


	


r11080 | dave.mehringer | 2010-04-13 09:03:45 -0600 (Tue, 13 Apr 2010) | 14 lines
Changed paths:
   M /active/casacore/casa/BasicSL/String.cc
   M /active/casacore/casa/BasicSL/String.h
   M /active/casacore/casa/BasicSL/test/tString.cc


       New Development: Yes
            JIRA Issue: CAS-1222 
      Ready to Release: Yes
     Interface Changes: Yes
What Interface Changed: added String::toInt() static method
         Test Programs: tString
  Put in Release Notes: No
             Module(s): casa
           Description: added toInt() static function

	


r11092 | jonas.larsen | 2010-04-14 08:02:15 -0600 (Wed, 14 Apr 2010) | 11 lines
Changed paths:
   M /active/casacore/casa/version.h


       New Development: No
            JIRA Issue: No
      Ready to Release: Yes
     Interface Changes: No
What Interface Changed: 
         Test Programs: Build CASA
  Put in Release Notes: No
             Module(s): 
           Description: Update version dependency between CASA + casacore.

r11102 | dave.mehringer | 2010-04-14 15:01:04 -0600 (Wed, 14 Apr 2010) | 14 lines
Changed paths:
   A /active/casacore/images/Images/ImageInputParameters.cc
   A /active/casacore/images/Images/ImageInputParameters.h
   A /active/casacore/images/Images/test/imageinputtest.fits
   A /active/casacore/images/Images/test/tImageInputParameters.cc


       New Development: Yes
            JIRA Issue: CAS-1222 and more general task of moving region determination for image analysis to a single C++ class 
      Ready to Release: No (not needed for 3.0.1)
     Interface Changes: new class
What Interface Changed: Please list interface changes
         Test Programs: tImageInputParameters
  Put in Release Notes: No
             Module(s): Module Names change impacts.
           Description: new class for storage and access of common input parms for image analysis tasks

	


r11111 | dave.mehringer | 2010-04-14 16:35:43 -0600 (Wed, 14 Apr 2010) | 14 lines
Changed paths:
   M /active/casacore/images/Images/ImageInputParameters.cc


       New Development: No
            JIRA Issue: CAS-1222 
      Ready to Release: No
     Interface Changes: No
What Interface Changed: Please list interface changes
         Test Programs: List test programs
  Put in Release Notes: Yes/No
             Module(s): Module Names change impacts.
           Description: eliminate unused variable

	


r11114 | takeshi.nakazato | 2010-04-14 20:47:12 -0600 (Wed, 14 Apr 2010) | 26 lines
Changed paths:
   M /active/casacore/images/Images/ImageMoments.h
   M /active/casacore/images/Images/ImageMoments.tcc
   M /active/casacore/images/Images/MomentCalculator.h
   M /active/casacore/images/Images/MomentCalculator.tcc
   A /active/casacore/images/Images/MomentsBase.h
   A /active/casacore/images/Images/MomentsBase.tcc
   A /active/casacore/ms/MeasurementSets/MSAnalysis.cc
   A /active/casacore/ms/MeasurementSets/MSAnalysis.h
   A /active/casacore/ms/MeasurementSets/MSMoments.h
   A /active/casacore/ms/MeasurementSets/MSMoments.tcc
   M /active/casacore/scons-tools/dependencies.py


       New Development: Yes
            JIRA Issue: Yes CAS-1812
      Ready to Release: For 3.0.2
     Interface Changes: Yes
What Interface Changed: See below
         Test Programs: Run MSAnalysis::moments() on MS with FLOAT_DATA
  Put in Release Notes: Yes
             Module(s): may not affect existing modules, but unclear
           Description: Describe your changes here...

I have defined MSAnalysis and MSMoments classes to implement 
msmoments task that generates moments from single-dish MS.

To enable MSMoments class to share functionalities in MomentCalculators 
with ImageMoments class, I have newly defined MomentsBase class 
as a superclass of ImageMoments and MSMoments. The MomentCalculator 
classes take MomentsBase class as its input to accept both ImageMoments 
and MSMoments.

The ImageMoments class is re-defined as an inheritance of 
MomentsBase class.

	


r11115 | takeshi.nakazato | 2010-04-14 23:50:09 -0600 (Wed, 14 Apr 2010) | 15 lines
Changed paths:
   M /active/casacore/ms/MeasurementSets/MSAnalysis.cc
   M /active/casacore/ms/MeasurementSets/MSMoments.tcc


       New Development: No
            JIRA Issue: Yes CAS-1812
      Ready to Release: Yes
     Interface Changes: No
What Interface Changed: Please list interface changes
         Test Programs: List test programs
  Put in Release Notes: Yes/No
             Module(s): Module Names change impacts.
           Description: Describe your changes here...

Bit of changes on error handling.
	


r11120 | dave.mehringer | 2010-04-15 08:21:14 -0600 (Thu, 15 Apr 2010) | 14 lines
Changed paths:
   M /active/casacore/images/Images/ImageInputParameters.cc


       New Development: Yes/No
            JIRA Issue: No/Yes List JIRA ticket.
      Ready to Release: No
     Interface Changes: Yes/No
What Interface Changed: Please list interface changes
         Test Programs: List test programs
  Put in Release Notes: Yes/No
             Module(s): Module Names change impacts.
           Description: cosmetic indentation change 

	


r11138 | jonas.larsen | 2010-04-16 02:45:43 -0600 (Fri, 16 Apr 2010) | 14 lines
Changed paths:
   M /active/casacore/ms/MeasurementSets/MSMoments.h


       New Development: No
            JIRA Issue: No
      Ready to Release: Yes
     Interface Changes: No
What Interface Changed: 
         Test Programs: Build casacore
  Put in Release Notes: No
             Module(s): 
           Description: Public base class methods were redeclared as protected in the derived class, which did not compile for me, so I redeclared them as public (can't this duplication be avoided?).

./images/Images/MomentsBase.h:336: error: `casa::String casa::MomentsBase<T>::errorMessage() const [with T = casa::Float]' is inaccessible
ms/MeasurementSets/MSAnalysis.cc:282: error: within this context

r11149 | rob.reid | 2010-04-16 15:13:40 -0600 (Fri, 16 Apr 2010) | 22 lines
Changed paths:
   M /active/casacore/msfits/MSFits/MSFitsOutput.cc


       New Development: No
            JIRA Issue: Yes CAS-1835?, 1686, 2048, + 2103
      Ready to Release: Yes
     Interface Changes: No
What Interface Changed: 
         Test Programs: Doesn't break ngc5921uvcontsub2 regression.
  Put in Release Notes: No
             Module(s): msfits
           Description: Some typo and data type corrections for WX tables from
                        exportuvfits.

                        Also, progress but not a fix for the padwithflags
                        option of exportuvfits.

                        Finally, it adds a much better (i.e. correct) and
                        pre-file-creation test for when combinespw is 
                        impossible with padwithflags = False.

	


r11152 | wes.young | 2010-04-16 20:12:44 -0600 (Fri, 16 Apr 2010) | 1 line
Changed paths:
   M /active/casacore/msfits/MSFits/MSFitsOutput.cc

Removed an extraneous ;




git-svn-id: https://svn.cv.nrao.edu/svn/casa/test@11151 ac9c0da5-131f-0410-9009-a9c195f183e6