r7673 | laura.glendenning | 2009-04-16 16:14:19 -0600 (Thu, 16 Apr 2009) | 13 lines Changed paths:    M /v2/active/code/casaqt/implement/QtUtilities/PlotColorWidget.ui    M /v2/active/code/casaqt/implement/QtUtilities/PlotFileWidget.ui    M /v2/active/code/casaqt/implement/QtUtilities/PlotFillWidget.ui    M /v2/active/code/casaqt/implement/QtUtilities/PlotLabelWidget.ui    M /v2/active/code/casaqt/implement/QtUtilities/PlotLineWidget.ui    M /v2/active/code/casaqt/implement/QtUtilities/QtPlotWidget.cc    M /v2/active/code/plotms/implement/Gui/PlotMSAveragingWidget.ui    M /v2/active/code/plotms/implement/Gui/PlotMSSelectionWidget.cc    M /v2/active/code/plotms/implement/Gui/PlotRangeWidget.ui    M /v2/active/code/plotms/implement/GuiTabs/PlotMSPlotTab.cc    M /v2/active/code/plotms/implement/GuiTabs/PlotMSPlotTab.qo.h    M /v2/active/code/plotms/implement/GuiTabs/PlotMSPlotTab.ui    M /v2/active/code/plotms/implement/GuiTabs/PlotMSTab.cc    M /v2/active/code/plotms/implement/PlotMS/PlotMSConstants.cc    M /v2/active/code/plotms/implement/PlotMS/PlotMSConstants.h    M /v2/active/code/plotms/implement/Plots/PlotMSSinglePlot.cc    M /v2/active/code/plotms/implement/Plots/PlotMSSinglePlotParameters.cc    M /v2/active/code/plotms/implement/Plots/PlotMSSinglePlotParameters.h
       New Development: No
            JIRA Issue: No
      Ready to Release: Yes
     Interface Changes: No
What Interface Changed: N/A
         Test Programs: qwtplottertest, casaplotms (manually)
  Put in Release Notes: No
             Module(s): casaqt, plotms
           Description: * Tweaked the GUI widgets for PlotMS slightly.
                        * Added grid line functionality to PlotMS.


r7676 | darrell.schiebel | 2009-04-16 19:33:18 -0600 (Thu, 16 Apr 2009) | 33 lines
Changed paths:
   M /v2/active/code/msvis/apps/casasplit/makefile

       New Development: no
            JIRA Issue: no
      Ready to Release: yes
     Interface Changes: none
What Interface Changed: none
         Test Programs: none
  Put in Release Notes: no

           Description: Somehow libpgsbox.so seems to be a dependency (probably through another library). This introduces a dependency on PGPLOT (which introduces a dependency on X11). Without this change I get undefined symbols:

           /usr/bin/g++ -Wno-deprecated -DHAVE_QT4 -DAIPS_NEEDS_RETHROW  -DCASACORE_NEEDS_RETHROW -DAIPS_STDLIB -DAIPS_NO_LEAMALL\
OC -DAIPS_AUTO_STL -DAIPS_USEMATPLOTLIB  -DAIPS_HAS_QWT -DAIPS_64B -DAIPS_STDLIB -DAIPS_AUTO_STL -DAIPS_USEATM   -I/home/casa/act\
ive/linux_64b/tmp/msvis -I/home/casa/active/code/msvis/apps/casasplit -I/home/casa/active/code/include -I/home/casa/active/includ\
e/casacore -O2 -fPIC -pipe -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
              -s -Xlinker -rpath -Xlinker /usr/lib64/casapy/lib:/home/casa/active/linux_64b/lib:/usr/lib -Wl,-rpath -Wl,/usr/loca\
l/Trolltech/qt/lib64 -o /home/casa/active/linux_64b/bin/casasplit /home/casa/active/code/msvis/apps/casasplit/casasplit.cc  \
              -L/home/casa/active/linux_64b/lib \
                \
              -lmsvis \
               -L/home/casa/active/linux_64b/lib -lcasa_casa -lcasa_components -lcasa_coordinates -lcasa_fits -lcasa_images -lcas\
a_lattices -lcasa_mirlib -lcasa_ms -lcasa_msfits -lcasa_tables -lcasa_scimath -lcasa_scimath_f -lcasa_measures -lcasa_measures_f \
-lfftw3 -lfftw3f -lfftw3_threads -lfftw3f_threads
/usr/lib64/libpgsbox.so.4.3: undefined reference to `pgmove_'
/usr/lib64/libpgsbox.so.4.3: undefined reference to `pgqcs_'
/usr/lib64/libpgsbox.so.4.3: undefined reference to `pgdraw_'
/usr/lib64/libpgsbox.so.4.3: undefined reference to `pgqwin_'
/usr/lib64/libpgsbox.so.4.3: undefined reference to `pgsvp_'
/usr/lib64/libpgsbox.so.4.3: undefined reference to `pgqci_'
/usr/lib64/libpgsbox.so.4.3: undefined reference to `pgline_'
/usr/lib64/libpgsbox.so.4.3: undefined reference to `pgnumb_'



r7685 | laura.glendenning | 2009-04-20 10:18:10 -0600 (Mon, 20 Apr 2009) | 13 lines
Changed paths:
   M /v2/active/code/casaqt/implement/QtBrowser/TBDataTab.cc
   M /v2/active/code/casaqt/implement/QtBrowser/TBKeywordsTab.cc


       New Development: No
            JIRA Issue: CAS-1320
      Ready to Release: Yes
     Interface Changes: No
What Interface Changed: N/A
         Test Programs: N/A
  Put in Release Notes: No
             Module(s): casaqt
           Description: Bug fix for seg fault when mixing arrays and non-arrays
                        in the browser's side panel.


r7687 | laura.glendenning | 2009-04-20 13:29:33 -0600 (Mon, 20 Apr 2009) | 15 lines
Changed paths:
   M /v2/active/code/casaqt/implement/QtBrowser/TBConstants.cc
   M /v2/active/code/casaqt/implement/QtBrowser/TBConstants.h
   M /v2/active/code/casaqt/implement/QtBrowser/TBViewArray.cc


       New Development: No
            JIRA Issue: No
      Ready to Release: Yes (but not necessary for release)
     Interface Changes: No
What Interface Changed: N/A
         Test Programs: N/A
  Put in Release Notes: No
             Module(s): casaqt
           Description: Minor improvement when viewing records within records
                        in the table browser, such that the table cell starts
                        off showing <= 4 rows of the record rather than just
                        the header.


r7690 | laura.glendenning | 2009-04-20 16:17:46 -0600 (Mon, 20 Apr 2009) | 15 lines
Changed paths:
   M /v2/active/code/casaqt/implement/QtBrowser/TBConnection.cc
   A /v2/active/code/casaqt/implement/QtBrowser/TBFileDialog.cc
   A /v2/active/code/casaqt/implement/QtBrowser/TBFileDialog.qo.h
   M /v2/active/code/casaqt/implement/QtBrowser/TBMain.cc
   M /v2/active/code/casaqt/implement/QtBrowser/TBTaQL.cc


       New Development: No
            JIRA Issue: CAS-1321
      Ready to Release: Yes (but isn't needed for the release)
     Interface Changes: No
What Interface Changed: N/A
         Test Programs: N/A
  Put in Release Notes: No
             Module(s): casaqt
           Description: Made a subclass of QFileDialog for the table browser
                        to implement behavior described in the second part of
                        CAS-1321.  It's kind of ugly, but it should get the
                        job done.


r7691 | laura.glendenning | 2009-04-20 16:44:27 -0600 (Mon, 20 Apr 2009) | 16 lines
Changed paths:
   M /v2/active/code/casaqt/implement/QtBrowser/TBBrowser.cc


       New Development: No
            JIRA Issue: No
      Ready to Release: Yes
     Interface Changes: No
What Interface Changed: N/A
         Test Programs: N/A
  Put in Release Notes: No
             Module(s): casaqt
           Description: Fixed bug in browser that didn't used to be there
                        (think it may have been precipitated by changes in
                        casacore) where trying to open a directory that wasn't
                        a CASA table would cause an error to be thrown and
                        crash the program.




git-svn-id: https://svn.cv.nrao.edu/svn/casa/v2/stable@7695 ac9c0da5-131f-0410-9009-a9c195f183e6