New Development: no             JIRA Issue: no       Ready to Release: yes      Interface Changes: none What Interface Changed: none          Test Programs: none   Put in Release Notes: no
           Description: User reports that with the linux binary distribution & fedora 12 they get these errors:

	   		localhost.localdomain<27>% casapy-test
			CASA Version 3.1.0 (r12585)
			 Compiled on: Fri 2010/09/03 06:16:20 UTC
			 ERROR: ld.so: object '/home/we/Programs/casapy-test-31.0.12585-001-64b/lib64/libpython2.6.so' from LD_PRELOAD cannot be preloaded: ignored.
			 ERROR: ld.so: object '/home/we/Programs/casapy-test-31.0.12585-001-64b/lib64/libQtCore.so.4' from LD_PRELOAD cannot be preloaded: ignored.
			 ERROR: ld.so: object '/home/we/Programs/casapy-test-31.0.12585-001-64b/lib64/libQtGui.so.4' from LD_PRELOAD cannot be preloaded: ignored.
			 ERROR: ld.so: object '/home/we/Programs/casapy-test-31.0.12585-001-64b/lib64/libQtSvg.so.4' from LD_PRELOAD cannot be preloaded: ignored.

		I believe this is because the newer runtime linkers must complain when one of the "LD_PRELOAD" libraries is already loaded. The user confirmed that this change resolves the issue.




git-svn-id: https://svn.cv.nrao.edu/svn/casa/active@12615 ac9c0da5-131f-0410-9009-a9c195f183e6