Changes from the group ------------------------------------------------------------------------ r12613 | remy.indebetouw | 2010-09-06 09:42:27 -0600 (Mon, 06 Sep 2010) | 13 lines Changed paths:    M /active/code/xmlcasa/scripts/simutil.py    M /active/code/xmlcasa/scripts/task_simdata.py    M /active/code/xmlcasa/tasks/simdata.xml
       New Development: Yes
            JIRA Issue: 1929,2294
        Ready for Test: Yes
     Interface Changes: No
         Test Programs: regressions
  Put in Release Notes: No
             Module(s): Simulator
           Description: documented Tsys for ALMA, named log file for
            simdata.last, and bugfix for component-only simulation (display)

	



r12614 | remy.indebetouw | 2010-09-06 12:28:05 -0600 (Mon, 06 Sep 2010) | 12 lines
Changed paths:
   M /active/code/xmlcasa/scripts/simutil.py
   M /active/code/xmlcasa/scripts/task_simdata.py

       New Development: Yes
            JIRA Issue: 2294,1922
        Ready for Test: Yes
     Interface Changes: No
         Test Programs: none
  Put in Release Notes: No
             Module(s): Simulator
           Description: Tsys etc documented in online help, SMA TRx added to simdata:thermalnoise

	


r12616 | takeshi.nakazato | 2010-09-07 02:30:11 -0600 (Tue, 07 Sep 2010) | 16 lines
Changed paths:
   A /active/code/doc/casaref/CasaRef.dir/sd.htex
   A /active/code/doc/casaref/CasaRef.dir/sdModule.tex
   M /active/code/doc/casaref/CasaRef.latex


       New Development: Yes
            JIRA Issue: Yes CAS-2119
        Ready for Test: No
     Interface Changes: No
What Interface Changed: Please list interface changes
         Test Programs: List test programs
  Put in Release Notes: No
             Module(s): Module Names change impacts.
           Description: Describe your changes here...

Added draft document for sd reference manual.
This is unfinished.
	


r12617 | sandra.castro | 2010-09-07 03:43:00 -0600 (Tue, 07 Sep 2010) | 12 lines
Changed paths:
   M /active/code/xmlcasa/scripts/tests/test_flagdata2.py


       New Development: Yes
            JIRA Issue: CAS-2249
        Ready for Test: Yes
     Interface Changes: No
What Interface Changed: Please list interface changes
         Test Programs: test_flagdata2
  Put in Release Notes: No
             Module(s): 
           Description: Added new class test_multimode2 and others.
	   

r12618 | sandra.castro | 2010-09-07 04:11:42 -0600 (Tue, 07 Sep 2010) | 12 lines
Changed paths:
   M /active/code/xmlcasa/scripts/tests/test_flagdata2.py


       New Development: Yes
            JIRA Issue: CAS-2249
        Ready for Test: Yes
     Interface Changes: No
What Interface Changed: Please list interface changes
         Test Programs: test_flagdata2
  Put in Release Notes: No
             Module(s): 
           Description: Added test of autocorrelation flagging.
	   

r12619 | darrell.schiebel | 2010-09-07 07:39:48 -0600 (Tue, 07 Sep 2010) | 22 lines
Changed paths:
   M /active/code/xmlcasa/scripts/casapy.py

       New Development: no
            JIRA Issue: no
      Ready to Release: yes
     Interface Changes: none
What Interface Changed: none
         Test Programs: none
  Put in Release Notes: no

           Description: User reports that with the linux binary distribution & fedora 12 they get these errors:

	   		localhost.localdomain<27>% casapy-test
			CASA Version 3.1.0 (r12585)
			 Compiled on: Fri 2010/09/03 06:16:20 UTC
			 ERROR: ld.so: object '/home/we/Programs/casapy-test-31.0.12585-001-64b/lib64/libpython2.6.so' from LD_PRELOAD cannot be preloaded: ignored.
			 ERROR: ld.so: object '/home/we/Programs/casapy-test-31.0.12585-001-64b/lib64/libQtCore.so.4' from LD_PRELOAD cannot be preloaded: ignored.
			 ERROR: ld.so: object '/home/we/Programs/casapy-test-31.0.12585-001-64b/lib64/libQtGui.so.4' from LD_PRELOAD cannot be preloaded: ignored.
			 ERROR: ld.so: object '/home/we/Programs/casapy-test-31.0.12585-001-64b/lib64/libQtSvg.so.4' from LD_PRELOAD cannot be preloaded: ignored.

		I believe this is because the newer runtime linkers must complain when one of the "LD_PRELOAD" libraries is already loaded. The user confirmed that this change resolves the issue.



r12620 | wes.young | 2010-09-07 11:40:00 -0600 (Tue, 07 Sep 2010) | 15 lines
Changed paths:
   M /active/code/xmlcasa/install/buildmytasks


       New Development: No
            JIRA Issue: No
        Ready for Test: Yes
     Interface Changes: No
What Interface Changed: 
         Test Programs: Does it work
  Put in Release Notes: No
             Module(s): tasking
           Description: 
Linux and OSX differ in the way they do mktempfile so if OSX do it one way otherwise
do it the linux way. 
	


r12621 | kumar.golap | 2010-09-07 15:41:38 -0600 (Tue, 07 Sep 2010) | 15 lines
Changed paths:
   M /active/code/synthesis/implement/MeasurementComponents/MSCleanImageSkyModel.cc


       New Development: No
            JIRA Issue: No List JIRA ticket.
        Ready for Test: Yes
     Interface Changes: No
What Interface Changed: Please list interface changes
         Test Programs: List test programs
  Put in Release Notes: No
             Module(s): Module Names change impacts.
           Description: Describe your changes here...

Made sure private variables are set to reasonable defaults in constructor. This should fix a random memory alloc error noticed in 3C129D regression
	


r12623 | wes.young | 2010-09-07 17:28:02 -0600 (Tue, 07 Sep 2010) | 14 lines
Changed paths:
   M /active/code/doc/texinputs.dir/aips2help.sty
   M /active/code/doc/texinputs.dir/nraoheader.4ht


       New Development: No
            JIRA Issue: No
        Ready for Test: Yes
     Interface Changes: Yes
What Interface Changed: added ahsdfunction to aips2help
         Test Programs: 
  Put in Release Notes: No
             Module(s): documentation
           Description: 
Changes for to aips2help.sty to sort out issues with function names have _'s in them.
	


r12624 | wes.young | 2010-09-07 18:03:54 -0600 (Tue, 07 Sep 2010) | 14 lines
Changed paths:
   M /active/code/doc/casaref/CMakeLists.txt
   A /active/code/doc/casaref/CasaRef.dir/SingleDish.tex
   M /active/code/doc/casaref/CasaRef.dir/sd.htex
   M /active/code/doc/casaref/CasaRef.dir/sdModule.tex


       New Development: No
            JIRA Issue: No
        Ready for Test: No
     Interface Changes: No
What Interface Changed: 
         Test Programs: build it
  Put in Release Notes: No
             Module(s): docs
           Description: 
Various changes to documentation, mostly adding ahsdfunction to sd.htex, not done yet though.
	


r12625 | kumar.golap | 2010-09-07 18:11:22 -0600 (Tue, 07 Sep 2010) | 15 lines
Changed paths:
   M /active/code/synthesis/implement/MeasurementEquations/Imager.cc


       New Development: No
            JIRA Issue: Yes CAS-2434
        Ready for Test: Yes
     Interface Changes: No
What Interface Changed: Please list interface changes
         Test Programs: List test programs
  Put in Release Notes: No
             Module(s): Module Names change impacts.
           Description: Describe your changes here...

Throws an exception if image field of view is larger than pi in any direction
	


r12626 | wes.young | 2010-09-07 19:05:10 -0600 (Tue, 07 Sep 2010) | 1 line
Changed paths:
   M /active/code/doc/casaref/CasaRef.dir/sd.htex

finished the job on getting ahsdfunctions in place

r12628 | takeshi.nakazato | 2010-09-07 20:02:18 -0600 (Tue, 07 Sep 2010) | 16 lines
Changed paths:
   M /active/code/doc/texinputs.dir/aips2help.sty


       New Development: No
            JIRA Issue: Yes CAS-2119
        Ready for Test: No
     Interface Changes: No
What Interface Changed: Please list interface changes
         Test Programs: List test programs
  Put in Release Notes: Yes/No
             Module(s): Module Names change impacts.
           Description: Describe your changes here...

Added ahsdobject and modified ahsdfunction.




git-svn-id: https://svn.cv.nrao.edu/svn/casa/test@12631 ac9c0da5-131f-0410-9009-a9c195f183e6