Fix problems like:
      --> 192 print "Net memory allocated:", (int(mem2) - int(mem1))/1024, "MB" 193 194 if prof:
      ValueError: invalid literal for int() with base 10:
      'dyld: DYLD_ environment variables being ignored because main executable (/bin/ps) is setuid or setgid\n245444'




git-svn-id: https://svn.cv.nrao.edu/svn/casa/branches/release-4_3@31874 ac9c0da5-131f-0410-9009-a9c195f183e6