New Development: No             JIRA Issue: No       Ready to Release: Yes      Interface Changes: No What Interface Changed:          Test Programs: Build casacore   Put in Release Notes: No              Module(s):            Description: Public base class methods were redeclared as protected in the derived class, which did not compile for me, so I redeclared them as public (can't this duplication be avoided?).
./images/Images/MomentsBase.h:336: error: `casa::String casa::MomentsBase<T>::errorMessage() const [with T = casa::Float]' is inaccessible
ms/MeasurementSets/MSAnalysis.cc:282: error: within this context


git-svn-id: https://svn.cv.nrao.edu/svn/casa/active@11135 ac9c0da5-131f-0410-9009-a9c195f183e6